apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana
      version: "6.32.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
